### PR TITLE
MAIN: Fix pydicom string type bug from GRP-3

### PR DESCRIPTION
**Pull request by naterichman**
* Change type to isinstance for pydicom string subclasses
* Improve logging on not_found_tags

### CODE REVIEW

**Review by NPann — APPROVED** [review]
LGTM

**Review by NPann — APPROVED** [review]
Still LGTM!

**Comment by naterichman** [comment]
Do I need to bump a minor version for this? @NPann

**Comment by NPann** [comment]
> Do I need to bump a minor version for this? @NPann

I don't think so. Not a patch. Not an added feature. Would remove the enhancement label accordingly.

**Pull request merged**
